### ISSUE TITLE
God of War: Origins Collection [PS3] *.BIN - ERROR

### ISSUE THREAD

**Issue by ghost** [0xDC00/reconv#1]
It is possible to extract without error, but when rebuilding, the following error occurs:
```
[13:42:12] |I|: God of War: Origins Collection PS3 (.BIN)
[13:42:12] |I|: com.dc.gow_coo_gos_ps3
[13:42:12] |W|: Chains of Olympus & Ghost of Sparta
Extract/ReImport
_init_.yaml (optional)
---
table: |-
  á=a
  à=a
...
Note: ENGLISH/*.BIN
[13:42:12] |D|: ExR -r com.dc.gow_coo_gos_ps3 -i game.bin.csv -o game_repacked.zip
[13:42:12] |I|: Repacking...
[13:42:12] |I|: [Repack.Begin] /game.bin
[13:42:13] |E|: Arg_OverflowException
[13:42:13] |E|: 
   at ExR.Format.GOW_Ghost_of_Sparta.StringsBlockPS3(Byte[] rawBlock, List`1 lines)
   at ExR.Format.GOW_Ghost_of_Sparta.RepackText(List`1 lines)
   at ExR.TextConv.RepackLines(List`1 lines, String outBinName)
   at ExR.TextConv.Repack(IFileSystem fsIn, IFileSystem fsOut)
[13:42:13] |I|: All done.
[13:42:13] |I|: game.bin 467.31 KB

[13:42:13] |D|: Time Elapsed 00:00:00
[13:42:13] |I|: Build success
[13:42:13] |D|: Done!
```

**Comment by ghost** [comment]
up.

**Comment by ghost** [comment]
up²

**Comment by ghost** [comment]
Samples files
[Samples.zip](https://github.com/0xDC00/reconv/files/9379003/Samples.zip)
